import{useEffect,useState}from'react';import{ArrowRight,Bot,CheckCircle2,CircleCheckBig,Cpu,Headphones,LoaderCircle,Mail,MapPin,MessageCircle,Phone,Rocket,Send,ShieldCheck,Sparkles,Users}from'lucide-react';import Navbar from'./components/Navbar';import Footer from'./components/Footer';import ServiceCard from'./components/ServiceCard';import FAQItem from'./components/FAQItem';import Chatbot from'./components/Chatbot';import{services,initialFaqs,stats}from'./data/siteData';import{askGemini,generateFaqWithGemini}from'./services/geminiService';

// Question 2: Clean main functional component
export default function App(){
 // Question 7: Chatbot visibility state
 const[isChatbotOpen,setIsChatbotOpen]=useState(false);
 // Question 13: FAQ data state initialized empty
 const[faqContent,setFaqContent]=useState([]);
 // Question 15: FAQ loading state
 const[isFaqLoading,setIsFaqLoading]=useState(true);const[openFaq,setOpenFaq]=useState(0);const[notice,setNotice]=useState('');const[status,setStatus]=useState('');
 // Question 11: App-level async Gemini chatbot function
 const sendPromptToGemini=(prompt,history)=>askGemini(prompt,history);
 // Question 14: Gemini API function for FAQ JSON
 const generateFAQ=async()=>{setIsFaqLoading(true);setNotice('');try{const data=await generateFaqWithGemini();if(!data.length)throw new Error();setFaqContent(data)}catch{setFaqContent(initialFaqs);setNotice('Showing prepared FAQ content because live Gemini generation is temporarily unavailable.')}finally{setIsFaqLoading(false)}};
 useEffect(()=>{generateFAQ()},[]);
 return <div className="min-h-screen"><Navbar/><main>
 {/* Question 3: Hero */}<section id="hero" className="grid-bg flex min-h-screen items-center pt-28"><div className="shell grid items-center gap-14 py-16 lg:grid-cols-2"><div><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/5 px-4 py-2 text-xs font-bold tracking-[.15em] text-cyan-300"><Sparkles className="h-4 w-4"/>FUTURE-READY DIGITAL SOLUTIONS</span><h1 className="mt-6 text-4xl font-black leading-tight sm:text-5xl md:text-6xl lg:text-7xl">Technology that moves your <span className="gradient-text">business forward.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">Nexora designs secure websites, cloud platforms and intelligent experiences that help organizations grow faster and operate smarter.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={()=>document.getElementById('contact')?.scrollIntoView({behavior:'smooth'})} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-400 to-blue-600 px-6 py-4 font-bold">Start Your Project<ArrowRight/></button><button onClick={()=>setIsChatbotOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-6 py-4 font-bold"><Bot className="text-cyan-300"/>Ask Nexora AI</button></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-400">{['Responsive by design','Security focused','Built to scale'].map(x=><span key={x} className="flex gap-2"><CheckCircle2 className="h-4 w-4 text-cyan-300"/>{x}</span>)}</div></div><div className="glass rounded-[2rem] p-5"><div className="rounded-3xl bg-[#06101d] p-6"><div className="mb-8 flex justify-between"><div><small className="font-bold tracking-[.18em] text-cyan-300">DIGITAL OPERATIONS</small><h2 className="mt-2 text-2xl font-black">System Overview</h2></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-500/10 text-blue-300"><Cpu/></span></div><div className="grid grid-cols-2 gap-3">{[[ShieldCheck,'Security','99.9%'],[Rocket,'Performance','+46%'],[Headphones,'Support','24/7'],[CircleCheckBig,'Uptime','Stable']].map(([Icon,label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><Icon className="mb-5 h-5 w-5 text-cyan-300"/><b className="block text-xl sm:text-2xl">{value}</b><small className="text-slate-500">{label}</small></div>)}</div></div></div></div></section>
 {/* Question 3: Services */}<section id="services" className="py-24"><div className="shell"><div className="mx-auto mb-12 max-w-3xl text-center"><p className="font-black tracking-[.2em] text-cyan-300">OUR CAPABILITIES</p><h2 className="mt-4 text-3xl font-black sm:text-4xl lg:text-5xl">Complete technology services for modern business</h2></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=><ServiceCard key={s.title}{...s}/>)}</div></div></section>
 {/* Question 3: About */}<section id="about" className="bg-white/[.025] py-24"><div className="shell grid items-center gap-12 lg:grid-cols-2"><div className="glass grid min-h-[420px] place-items-center rounded-[2rem] p-8 text-center"><div><span className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-cyan-400/10 text-cyan-300"><Users className="h-10 w-10"/></span><p className="mt-7 font-bold tracking-[.2em] text-cyan-300">PEOPLE + TECHNOLOGY</p><h3 className="mt-3 text-3xl font-black">One expert team.<br/>One clear mission.</h3></div></div><div><p className="font-black tracking-[.2em] text-cyan-300">ABOUT NEXORA</p><h2 className="mt-4 text-3xl font-black sm:text-4xl lg:text-5xl">We turn complex technology into measurable progress.</h2><p className="mt-6 leading-8 text-slate-400">Our team combines product thinking, engineering discipline and dependable support to build practical solutions today and adaptable systems for tomorrow.</p><div className="mt-8 grid grid-cols-2 gap-4">{stats.map(([v,l])=><div key={l} className="glass rounded-2xl p-5"><b className="block text-3xl">{v}</b><small className="text-slate-500">{l}</small></div>)}</div></div></div></section>
 {/* Questions 13-16: FAQ */}<section id="faq" className="py-24"><div className="shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-black tracking-[.2em] text-cyan-300">GEMINI-POWERED FAQ</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">Questions clients commonly ask</h2><p className="mt-5 leading-8 text-slate-400">Gemini generates structured FAQ content and React renders it dynamically.</p><button onClick={generateFAQ} disabled={isFaqLoading} className="mt-7 inline-flex items-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/5 px-5 py-3 font-bold text-cyan-300">{isFaqLoading?<LoaderCircle className="animate-spin"/>:<Sparkles/>}Generate FAQ Again</button>{notice&&<p className="mt-4 text-xs text-amber-300">{notice}</p>}</div><div className="space-y-4">{/* Question 16: Conditional loading + map */}{isFaqLoading?<div className="glass grid min-h-56 place-items-center rounded-3xl"><div className="text-center"><LoaderCircle className="mx-auto animate-spin text-cyan-300"/><p className="mt-4">Gemini is generating FAQ content...</p></div></div>:faqContent.map((item,i)=><FAQItem key={item.question+i} item={item} isOpen={openFaq===i} onToggle={()=>setOpenFaq(openFaq===i?-1:i)}/>)}</div></div></section>
 {/* Question 3: Contact */}<section id="contact" className="bg-white/[.025] py-24"><div className="shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-black tracking-[.2em] text-cyan-300">LET’S BUILD TOGETHER</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Tell us about your next digital project.</h2><p className="mt-5 leading-8 text-slate-400">Share your goal and our team will respond with practical next steps.</p><div className="mt-8 space-y-4 text-slate-300"><p className="flex gap-3"><Mail className="text-cyan-300"/>hello@nexora.com</p><p className="flex gap-3"><Phone className="text-cyan-300"/>+91 98765 43210</p><p className="flex gap-3"><MapPin className="text-cyan-300"/>Chennai, India</p></div></div><form onSubmit={e=>{e.preventDefault();setStatus('Thank you! Your project enquiry has been received.');e.currentTarget.reset()}} className="glass rounded-[2rem] p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><input required placeholder="Full name" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/><input required type="email" placeholder="Email address" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/></div><select className="mt-5 w-full rounded-xl border border-white/10 bg-[#0d1c31] px-4 py-3">{services.map(s=><option key={s.title}>{s.title}</option>)}</select><textarea required rows="5" placeholder="Project details" className="mt-5 w-full resize-none rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/><button className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-400 to-blue-600 px-6 py-4 font-bold">Send Enquiry<Send/></button>{status&&<p className="mt-4 rounded-xl bg-emerald-400/10 p-3 text-emerald-300">{status}</p>}</form></div></section>
 </main><Footer/><Chatbot isOpen={isChatbotOpen} onClose={()=>setIsChatbotOpen(false)} onSend={sendPromptToGemini}/>{!isChatbotOpen&&<button onClick={()=>setIsChatbotOpen(true)} className="fixed bottom-5 right-4 z-40 grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-cyan-400 to-blue-600 shadow-2xl" aria-label="Open chatbot"><MessageCircle className="h-7 w-7"/></button>}</div>}
